
DataEmpleado = [{
    "IdEmpleado" : 1,
    "nombre" : "Claudio",
    "apellido" : "Echeverry",
    "Documento" : 37054555,
    "Email" : "ElDiablo@gmail.com",
    "Ocupacion" : "Gasista",
    "Reputacion" : "4.4 / 5",
    "Direccion" : "Avenida 32 436",
    "CP" : 7223,
    "Telefono" : 2241536987,
    "Foto" : "ImagenDePerfil.jpeg",
    "Rol" : "Empleado",
    "TrabajosRealizados" : 19,
    "Resumen" : "Gasista matriculado con 12 años de experiencia en el rubro. Hago instalaciones eléctricas, instalaciones de artefactos eléctricos y reparaciones en general."
},
{
    "IdEmpleado" : 2,
    "nombre": "Alejandra",
    "apellido": "González",
    "Documento": 48123698,
    "Email": "Alejandra.G@gmail.com",
    "Ocupacion": "Pintor",
    "Reputacion": "4.8 / 5" ,
    "Direccion": "Calle 54 789",
    "CP": 54321,
    "Telefono": 5557891234,
    "Foto": "AlejandraPerfil.jpg",
    "Rol": "Empleado",
    "TrabajosRealizados": 27,
    "Resumen" : "Pintor con mas de 6 años de experiencia en el rubro."
},
{
    "IdEmpleado" : 3,
    "nombre": "Roberto",
    "apellido": "Mendoza",
    "Documento": 81527933,
    "Email": "Roberto_M@gmail.com",
    "Ocupacion": "Albañil",
    "Reputacion": "4.2 / 5",
    "Direccion": "Carrera 12 567",
    "CP": 12345,
    "Telefono": 7774567890,
    "Foto": "RobertoAvatar.png",
    "Rol": "Empleado",
    "TrabajosRealizados": 34,
    "Resumen" : "Albañil con experiencia comprobable, responsable y cumplidor"
},
{
    "IdEmpleado" : 4,
    "nombre": "Laura",
    "apellido": "Pérez",
    "Documento": 63980215,
    "Email": "Laura_P@gmail.com",
    "Ocupacion": "Jardinera",
    "Reputacion": "4.6 / 5",
    "Direccion": "Avenida 78 123",
    "CP": 98765,
    "Telefono": 3336547890,
    "Foto": "LauraFoto.jpg",
    "Rol": "Empleada",
    "TrabajosRealizados": 42,
    "Resumen" : "Jardinera certificada por la academia de Jardineros de Cierra Chica"
},
{
    "IdEmpleado" : 5,
    "nombre": "Javier",
    "apellido": "López",
    "Documento": 92547863,
    "Email": "Javier_L@gmail.com",
    "Ocupacion": "Reparacion A/A",
    "Reputacion": "4.0 / 5",
    "Direccion": "Plaza 45 789",
    "CP": 56789,
    "Telefono": 9991234567,
    "Foto": "JavierPic.png",
    "Rol": "Empleado",
    "TrabajosRealizados": 15, 
    "Resumen" : "Cuento con matricula y certificacion en el rubro"
},
{
    "IdEmpleado" : 6,
    "nombre": "Ana",
    "apellido": "Ramírez",
    "Documento": 73160984,
    "Email": "Ana_R@gmail.com",
    "Ocupacion": "Cuidado de adultos",
    "Reputacion": "4.5 / 5",
    "Direccion": "Calle 98 654",
    "CP": 45678,
    "Telefono": 8889876543,
    "Foto": "AnaProfile.jpg",
    "Rol": "Empleado",
    "TrabajosRealizados": 23,
    "Resumen" : "Empatica y responsable, con experiencia en el cuidado de ninos y adultos."
}
]
